services:
  pose-matching:
    build: .
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - .:/workspace
    command: [
      "--mask", "/workspace/mask.png",
      "--camera", "/workspace/camera_info.json",
      "--model", "/workspace/mask-generation/model/pen.step",
      "--scale", "0.001",
      "--image", "/workspace/input.png",
      "--output", "/workspace/result.png",
      "--rerun", "/workspace"
    ]

  verify-pose:
    build: .
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - .:/workspace
    network_mode: host
    entrypoint: ["/opt/build/verify_pose"]
    command: [
      "--model", "/workspace/mask-generation/model/pen.step",
      "--camera", "/workspace/camera_info.json",
      "--image", "/workspace/input.png",
      "--pose", "/workspace/correct_pose.json",
      "--scale", "0.001"
    ]

  cache-builder:
    build: .
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - .:/workspace
    entrypoint: ["/opt/build/pose_cache_builder"]
    command: [
      "--camera", "/workspace/camera_info.json",
      "--model", "/workspace/mask-generation/model/ad.step",
      "--scale", "0.001",
      "--output", "/workspace/cache/ad.bin",
      "--depth-min", "0.10",
      "--depth-max", "0.30",
      "--depth-steps", "10",
      "--local-depth", "3",
      "--threads", "14"
    ]

  pose-matching-cached:
    build: .
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - .:/workspace
    entrypoint: ["/opt/build/pose_matching_cached"]
    environment:
      - OBJECT_NAME=${OBJECT_NAME:-pen}
    command: [
      "--model", "/workspace/mask-generation/model/${OBJECT_NAME:-pen}.step",
      "--image", "/workspace/input/${OBJECT_NAME:-pen}/rgb.png",
      "--mask", "/workspace/input/${OBJECT_NAME:-pen}/mask.png",
      "--camera", "/workspace/camera_info.json",
      "--scale", "0.001",
      "--cache", "/workspace/cache/${OBJECT_NAME:-pen}.bin",
      "--output", "/workspace/result/${OBJECT_NAME:-pen}/result_cached.png",
      "--rerun", "/workspace/record",
      "--max-candidates", "30",
      "--fatol", "1e-4",
      "--xatol", "1e-3",
      "--contour-points", "4000",
      "--lm-tolerance", "1e-9",
      "--refine-method", "nelder-mead",
      "--early-termination-iou", "0.95",
      "--int-mask", "/workspace/int",
      "--sort-metric", "centroid_iou"
    ]

  visualize-poses:
    build: .
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - .:/workspace
    network_mode: host
    entrypoint: ["/opt/build/visualize_poses"]
    command: [
      "--camera", "/workspace/camera_info.json",
      "--model", "/workspace/mask-generation/model/pen.step",
      "--scale", "0.001",
      "--pose", "/workspace/pose_result-0.json",
      "--pose", "/workspace/pose_result-1.json",
      "--pose", "/workspace/pose_result-2.json",
      "--rerun-grpc", "rerun+http://127.0.0.1:9876/proxy",
      # "--rerun", "/workspace/poses.rrd"
    ]
